import type { ProviderConfig, ProviderModelConfig } from "@mariozechner/pi-coding-agent";
import type { IntegrationProviderPayloadRewrite } from "./request_rewrite.ts";

type WarnFn = (message: string) => void;

export type GatewayProviderInfo = {
  config: ProviderConfig;
  // Model ids the gateway accepts for this provider. Unknown when falling back
  // to pi's built-in catalog, so custom models are treated conservatively.
  modelIds?: ReadonlySet<string>;
  // Exact model aliases generated by this extension to preserve duplicate names.
  modelAliases?: ReadonlyMap<string, string>;
  // Exact generated model ids that need ChatGPT /codex/responses payload shaping.
  chatGPTModelIds?: ReadonlySet<string>;
  // Base URLs this extension registered for the provider. Used to distinguish
  // exe.dev-routed models from pi's restored built-in/direct models.
  baseUrls: ReadonlySet<string>;
};

export interface CatalogCompat {
  supportsDeveloperRole?: boolean;
  maxTokensField?: string;
  supportsReasoningEffort?: boolean;
  thinkingFormat?: string;
  cacheControlFormat?: string;
}

export interface CatalogModel {
  id: string;
  name?: string;
  type?: string;
  reasoning?: boolean;
  input?: ("text" | "image")[];
  contextWindow?: number;
  maxTokens?: number;
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
  compat?: CatalogCompat;
}

export interface CatalogProvider {
  id: string;
  path: string;
  api?: string;
  models: CatalogModel[];
}

export interface Catalog {
  schemaVersion: number;
  providers: CatalogProvider[];
}

interface ReflectionIntegration {
  name?: string;
  type?: string;
  team?: boolean;
  help?: string;
}

interface ReflectionIntegrationsResponse {
  integrations?: ReflectionIntegration[];
}

interface IntegrationModelArchitecture {
  input_modalities?: string[];
  output_modalities?: string[];
}

interface IntegrationModelLimits {
  context_window?: number;
  max_output_tokens?: number;
}

interface IntegrationModelExeDev {
  mode?: string;
}

interface IntegrationModel {
  id: string;
  name?: string;
  provider: string;
  native_id?: string;
  apis?: string[];
  architecture?: IntegrationModelArchitecture;
  limits?: IntegrationModelLimits;
  exe_dev?: IntegrationModelExeDev;
}

interface IntegrationCatalog {
  schema_version: number;
  models: IntegrationModel[];
}

export type DiscoveredIntegration = {
  name: string;
  baseURL: string;
  catalog?: IntegrationCatalog;
};

type CompatBag = {
  supportsDeveloperRole?: boolean;
  supportsReasoningEffort?: boolean;
  maxTokensField?: "max_tokens" | "max_completion_tokens";
  thinkingFormat?: "openai" | "openrouter" | "deepseek" | "zai" | "qwen" | "qwen-chat-template";
  cacheControlFormat?: "anthropic";
};

export type JSONFetcher = (url: string) => Promise<unknown | undefined>;

// Keep in lockstep with llmcatalog.CatalogSchemaVersion. Any breaking change
// there requires shipping a new exe-dev pi extension that knows the new shape;
// until then the extension treats the catalog as unavailable and falls back.
export const SCHEMA_VERSION = 1;

const KNOWN_APIS: ReadonlySet<string> = new Set([
  "openai-completions",
  "openai-responses",
  "azure-openai-responses",
  "anthropic-messages",
  "bedrock-converse-stream",
  "google-generative-ai",
  "google-vertex",
  "mistral-conversations",
]);
const KNOWN_THINKING_FORMATS: ReadonlySet<string> = new Set([
  "openai",
  "openrouter",
  "deepseek",
  "zai",
  "qwen",
  "qwen-chat-template",
]);
const KNOWN_MAX_TOKENS_FIELDS: ReadonlySet<string> = new Set(["max_tokens", "max_completion_tokens"]);
const KNOWN_CACHE_CONTROL_FORMATS: ReadonlySet<string> = new Set(["anthropic"]);

export function validCatalog(cat: unknown): cat is Catalog {
  if (!cat || typeof cat !== "object") return false;
  const c = cat as Catalog;
  if (c.schemaVersion !== SCHEMA_VERSION) return false;
  if (!Array.isArray(c.providers) || c.providers.length === 0) return false;
  return true;
}

function validIntegrationCatalog(cat: unknown): cat is IntegrationCatalog {
  if (!cat || typeof cat !== "object") return false;
  const c = cat as IntegrationCatalog;
  if (c.schema_version !== SCHEMA_VERSION) return false;
  if (!Array.isArray(c.models)) return false;
  return true;
}

export async function fetchJSONWithTimeout(url: string, timeoutMS: number): Promise<unknown | undefined> {
  const res = await fetch(url, { signal: AbortSignal.timeout(timeoutMS) });
  if (!res.ok) return undefined;
  return (await res.json()) as unknown;
}

function reflectionLLMIntegrations(reflection: unknown): ReflectionIntegration[] | undefined {
  const integrations = (reflection as ReflectionIntegrationsResponse | undefined)?.integrations;
  if (!Array.isArray(integrations)) return undefined;
  return integrations
    .filter((integration) => integration.type === "llm" && typeof integration.name === "string" && integration.name.length > 0)
    .sort((a, b) => (a.name ?? "").localeCompare(b.name ?? ""));
}

async function fetchReflectionIntegrations(
  url: string,
  fetchJSON: JSONFetcher,
  warn: WarnFn,
): Promise<ReflectionIntegration[]> {
  let integrations: ReflectionIntegration[] | undefined;
  try {
    const reflection = await fetchJSON(url);
    integrations = reflectionLLMIntegrations(reflection);
    if (!integrations) throw new Error(`${url} returned unrecognized reflection shape`);
  } catch (err) {
    warn(`[pi-exe-dev] LLM integration reflection fetch failed: ${(err as Error).message}`);
    return [];
  }
  return integrations.sort((a, b) => {
    const byName = (a.name ?? "").localeCompare(b.name ?? "");
    if (byName !== 0) return byName;
    return Number(a.team === true) - Number(b.team === true);
  });
}

function defaultIntegrationBaseURL(integration: ReflectionIntegration): string {
  const name = integration.name as string;
  return integration.team === true ? `https://${name}.team.exe.xyz` : `https://${name}.int.exe.xyz`;
}

function integrationBaseURLCandidates(integration: ReflectionIntegration): string[] {
  const candidates: string[] = [];
  const add = (baseURL: string) => {
    if (!candidates.includes(baseURL)) candidates.push(baseURL);
  };

  for (const match of integration.help?.matchAll(/https?:\/\/[^\s'"`]+/g) ?? []) {
    try {
      const url = new URL(match[0]);
      if (
        url.hostname.endsWith(".int.exe.xyz") ||
        url.hostname.endsWith(".team.exe.xyz")
      ) {
        add(url.origin);
      }
    } catch {
      // Ignore prose that looked like a URL but was not parseable.
    }
  }

  if (integration.name) {
    if (integration.team === true) {
      add(`https://${integration.name}.team.exe.xyz`);
    } else {
      add(`https://${integration.name}.int.exe.xyz`);
    }
  }
  return candidates;
}

function firstAggregateErrorMessage(err: unknown): string {
  if (err instanceof AggregateError && err.errors.length > 0) {
    return (err.errors[0] as Error).message;
  }
  return (err as Error).message;
}

async function fetchIntegrationCatalog(
  integration: ReflectionIntegration,
  fetchJSON: JSONFetcher,
  warn: WarnFn,
): Promise<DiscoveredIntegration> {
  const name = integration.name as string;
  const candidates = integrationBaseURLCandidates(integration);
  if (candidates.length === 0) return { name, baseURL: defaultIntegrationBaseURL(integration) };

  try {
    return await Promise.any(
      candidates.map(async (baseURL) => {
        const catalog = await fetchJSON(`${baseURL}/models.json`);
        if (!validIntegrationCatalog(catalog)) {
          throw new Error(`${baseURL}/models.json returned unrecognized catalog shape`);
        }
        return { name, baseURL, catalog };
      }),
    );
  } catch (err) {
    warn(`[pi-exe-dev] LLM integration ${name} models.json fetch failed: ${firstAggregateErrorMessage(err)}`);
    return { name, baseURL: defaultIntegrationBaseURL(integration) };
  }
}

export async function discoverIntegrationCatalogs(
  reflectionURL: string,
  fetchJSON: JSONFetcher,
  warn: WarnFn = console.warn,
): Promise<{ found: boolean; integrations: DiscoveredIntegration[] }> {
  const llmIntegrations = await fetchReflectionIntegrations(reflectionURL, fetchJSON, warn);
  if (llmIntegrations.length === 0) return { found: false, integrations: [] };
  const integrations = await Promise.all(llmIntegrations.map((integration) => fetchIntegrationCatalog(integration, fetchJSON, warn)));
  return { found: true, integrations };
}

function providerAPIForIntegrationModel(model: IntegrationModel): ProviderConfig["api"] | undefined {
  const apis = new Set(model.apis ?? []);
  switch (model.provider) {
    case "anthropic":
      return apis.has("anthropic_messages") ? "anthropic-messages" : undefined;
    case "openai":
      if (apis.has("openai_responses")) return "openai-responses";
      if (apis.has("openai_chat")) return "openai-completions";
      return undefined;
    case "fireworks":
      return apis.has("openai_chat") ? "openai-completions" : undefined;
    default:
      return undefined;
  }
}

function integrationProviderBaseURL(baseURL: string, provider: string): string | undefined {
  switch (provider) {
    case "anthropic":
      return baseURL;
    case "openai":
      return `${baseURL}/v1`;
    case "fireworks":
      return `${baseURL}/v1`;
    default:
      return undefined;
  }
}

function integrationModelID(model: IntegrationModel): string | undefined {
  const id = model.native_id || model.id;
  return typeof id === "string" && id.length > 0 ? id : undefined;
}

function integrationAliasModelID(modelID: string, integrationName: string): string {
  return `${modelID}@${integrationName}`;
}

function inputModalities(model: IntegrationModel, fallback: CatalogModel | undefined): ("text" | "image")[] {
  const out = (model.architecture?.input_modalities ?? []).filter(
    (input): input is "text" | "image" => input === "text" || input === "image",
  );
  if (out.length > 0) return out;
  if (fallback?.input?.length) return fallback.input;
  return ["text"];
}

function costCatalogIndex(catalog: Catalog | undefined): Map<string, CatalogModel> {
  const out = new Map<string, CatalogModel>();
  if (!catalog) return out;
  for (const provider of catalog.providers) {
    for (const model of provider.models) {
      out.set(`${provider.id}\0${model.id}`, model);
    }
  }
  return out;
}

function fallbackCatalogModel(
  costs: Map<string, CatalogModel>,
  provider: string,
  modelID: string,
  requestID: string,
): CatalogModel | undefined {
  return costs.get(`${provider}\0${modelID}`) ?? costs.get(`${provider}\0${requestID}`);
}

function configFromIntegrationModel(
  integration: DiscoveredIntegration,
  model: IntegrationModel,
  fallback: CatalogModel | undefined,
): ProviderModelConfig | undefined {
  const api = providerAPIForIntegrationModel(model);
  const baseUrl = integrationProviderBaseURL(integration.baseURL, model.provider);
  if (!api || !baseUrl) return undefined;

  const modelID = integrationModelID(model);
  if (!modelID) return undefined;
  const compat = sanitizeCompat(fallback?.compat, model.provider, modelID);
  return {
    id: modelID,
    name: model.name || fallback?.name || modelID,
    api,
    baseUrl,
    reasoning: fallback?.reasoning ?? false,
    input: inputModalities(model, fallback),
    contextWindow: model.limits?.context_window ?? fallback?.contextWindow ?? 128000,
    maxTokens: model.limits?.max_output_tokens ?? fallback?.maxTokens ?? 4096,
    cost: fallback?.cost ?? { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    ...(compat ? { compat: compat as ProviderModelConfig["compat"] } : {}),
  };
}

type IntegrationModelCandidate = {
  integration: DiscoveredIntegration;
  model: IntegrationModel;
  nativeID: string;
  config: ProviderModelConfig;
};

function integrationModelCandidateScore(candidate: IntegrationModelCandidate): number {
  const apis = new Set(candidate.model.apis ?? []);
  let score = 0;
  switch (candidate.model.exe_dev?.mode) {
    case "managed":
      score += 100;
      break;
    case "chatgpt":
      break;
    default:
      score += 25;
      break;
  }
  if (candidate.model.provider === "openai" && apis.has("openai_responses") && apis.has("openai_chat")) {
    score += 20;
  }
  score += apis.size;
  return score;
}

function compareIntegrationModelCandidates(a: IntegrationModelCandidate, b: IntegrationModelCandidate): number {
  const score = integrationModelCandidateScore(b) - integrationModelCandidateScore(a);
  if (score !== 0) return score;
  return a.integration.name.localeCompare(b.integration.name);
}

function integrationModelConfig(candidate: IntegrationModelCandidate): ProviderModelConfig {
  return {
    ...candidate.config,
    id: integrationAliasModelID(candidate.nativeID, candidate.integration.name),
    name: `${candidate.config.name} (${candidate.integration.name})`,
  };
}

function integrationModelNeedsChatGPTPayloadRewrite(model: IntegrationModel): boolean {
  return model.provider === "openai" && model.exe_dev?.mode === "chatgpt" && (model.apis ?? []).includes("openai_responses");
}

export function integrationProviderDisplayName(names: string[]): string {
  const uniq = Array.from(new Set(names)).sort();
  if (uniq.length === 0) return "llm";
  if (uniq.length <= 2) return uniq.join(", ");
  return `${uniq[0]} + ${uniq.length - 1} more`;
}

export function integrationPromptAvailabilityLabel(names: string[]): string {
  const uniq = Array.from(new Set(names)).sort();
  if (uniq.length <= 2) return uniq.join(", ");
  return `${uniq.slice(0, 2).join(", ")}, ...`;
}

export function providerInfosFromIntegrationCatalogs(
  integrations: DiscoveredIntegration[],
  pricingCatalog: Catalog | undefined,
  warn: WarnFn = console.warn,
): Map<string, GatewayProviderInfo> {
  const costs = costCatalogIndex(pricingCatalog);
  const grouped = new Map<string, { names: string[]; byNativeID: Map<string, IntegrationModelCandidate[]> }>();
  const warnedMissingPricing = new Set<string>();

  for (const integration of integrations) {
    if (!integration.catalog) continue;
    for (const model of integration.catalog.models) {
      const provider = model.provider;
      const modelID = integrationModelID(model);
      if (!modelID) continue;
      const fallback = fallbackCatalogModel(costs, provider, modelID, model.id);
      const config = configFromIntegrationModel(integration, model, fallback);
      if (!config) continue;
      if (!fallback) {
        const key = `${provider}/${modelID}`;
        if (!warnedMissingPricing.has(key)) {
          warnedMissingPricing.add(key);
          warn(`[pi-exe-dev] missing pricing for integration model ${key}; pi usage cost will be reported as zero`);
        }
      }

      let entry = grouped.get(provider);
      if (!entry) {
        entry = { names: [], byNativeID: new Map() };
        grouped.set(provider, entry);
      }
      entry.names.push(integration.name);
      const candidates = entry.byNativeID.get(modelID) ?? [];
      candidates.push({ integration, model, nativeID: modelID, config });
      entry.byNativeID.set(modelID, candidates);
    }
  }

  const out = new Map<string, GatewayProviderInfo>();
  for (const [provider, entry] of grouped) {
    const models: ProviderModelConfig[] = [];
    const modelIds = new Set<string>();
    const modelAliases = new Map<string, string>();
    const chatGPTModelIds = new Set<string>();
    for (const [, candidates] of entry.byNativeID) {
      candidates.sort(compareIntegrationModelCandidates);
      for (const candidate of candidates) {
        const modelConfig = integrationModelConfig(candidate);
        models.push(modelConfig);
        modelIds.add(modelConfig.id);
        modelAliases.set(modelConfig.id, candidate.nativeID);
        if (integrationModelNeedsChatGPTPayloadRewrite(candidate.model)) {
          chatGPTModelIds.add(modelConfig.id);
        }
      }
    }
    const first = models[0];
    if (!first?.baseUrl) continue;
    const config: ProviderConfig = {
      name: integrationProviderDisplayName(entry.names),
      baseUrl: first.baseUrl,
      apiKey: "integration",
      models,
    };
    out.set(
      provider,
      providerInfo(config, {
        modelIds,
        modelAliases: modelAliases.size > 0 ? modelAliases : undefined,
        chatGPTModelIds: chatGPTModelIds.size > 0 ? chatGPTModelIds : undefined,
      }),
    );
  }
  return out;
}

// sanitizeCompat copies only fields whose values pi-ai understands. Unknown
// values would misconfigure the model silently; dropping them lets pi-ai fall
// back to its URL-based auto-detection. Returns undefined if nothing is set.
function sanitizeCompat(c: CatalogCompat | undefined, providerId: string, modelId: string): CompatBag | undefined {
  if (!c) return undefined;
  const out: CompatBag = {};
  if (typeof c.supportsDeveloperRole === "boolean") out.supportsDeveloperRole = c.supportsDeveloperRole;
  if (typeof c.supportsReasoningEffort === "boolean") out.supportsReasoningEffort = c.supportsReasoningEffort;
  if (c.maxTokensField) {
    if (KNOWN_MAX_TOKENS_FIELDS.has(c.maxTokensField)) {
      out.maxTokensField = c.maxTokensField as CompatBag["maxTokensField"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown maxTokensField "${c.maxTokensField}" on ${providerId}/${modelId}`);
    }
  }
  if (c.thinkingFormat) {
    if (KNOWN_THINKING_FORMATS.has(c.thinkingFormat)) {
      out.thinkingFormat = c.thinkingFormat as CompatBag["thinkingFormat"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown thinkingFormat "${c.thinkingFormat}" on ${providerId}/${modelId}`);
    }
  }
  if (c.cacheControlFormat) {
    if (KNOWN_CACHE_CONTROL_FORMATS.has(c.cacheControlFormat)) {
      out.cacheControlFormat = c.cacheControlFormat as CompatBag["cacheControlFormat"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown cacheControlFormat "${c.cacheControlFormat}" on ${providerId}/${modelId}`);
    }
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

// chatModelsWithFullMetadata picks chat models whose metadata is complete
// enough for pi to register directly. Models with partial metadata are
// dropped (and logged) rather than silently registered with bogus values.
// At the provider level, returning an empty list lets pi keep its built-in
// catalog for that provider — see registerOne.
function chatModelsWithFullMetadata(p: CatalogProvider): ProviderModelConfig[] {
  const out: ProviderModelConfig[] = [];
  const skipped: string[] = [];
  for (const m of p.models) {
    if (m.type && m.type !== "chat") continue; // skip embedding/reranker
    // Use explicit nullish/empty checks so a (hypothetical) zero-valued
    // contextWindow or maxTokens isn't misread as "missing", and so an
    // explicit empty input array is treated as missing rather than valid.
    if (m.name == null || m.contextWindow == null || m.maxTokens == null || !m.input?.length) {
      // Partial metadata is a Go-side bug (entry in allowedModels, no
      // gatewayMeta). Surface it instead of hiding the model silently.
      if (m.name || m.contextWindow != null || m.maxTokens != null || m.input?.length) {
        skipped.push(m.id);
      }
      continue;
    }
    const compat = sanitizeCompat(m.compat, p.id, m.id);
    out.push({
      id: m.id,
      name: m.name,
      reasoning: m.reasoning ?? false,
      input: m.input,
      contextWindow: m.contextWindow,
      maxTokens: m.maxTokens,
      cost: m.cost,
      ...(compat ? { compat: compat as ProviderModelConfig["compat"] } : {}),
    });
  }
  if (skipped.length > 0) {
    console.warn(`[pi-exe-dev] dropping ${p.id} models with incomplete metadata: ${skipped.join(", ")}`);
  }
  return out;
}

// configFromCatalogProvider builds the gateway provider config from the
// catalog. p.id must be one of pi-ai's KnownProvider names (anthropic, openai,
// fireworks, ...) because pi merges its built-in catalog by provider name; the
// Go-side providerCatalog in llmcatalog/pricing.go is the source of truth for
// these IDs.
export function configFromCatalogProvider(p: CatalogProvider, gatewayBaseURL: string): ProviderConfig {
  const path = p.path.replace(/^\/+/, "");
  const config: ProviderConfig = {
    baseUrl: `${gatewayBaseURL}/${path}`,
    apiKey: "gateway",
  };
  if (p.api) {
    if (KNOWN_APIS.has(p.api)) {
      config.api = p.api as ProviderConfig["api"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown api "${p.api}" for provider ${p.id}; pi-ai will auto-detect`);
    }
  }
  const models = chatModelsWithFullMetadata(p);
  // Leaving config.models undefined tells pi to keep its built-in catalog for
  // this provider. anthropic and openai rely on this — the gateway does not
  // ship rich metadata for them, only cost.
  if (models.length > 0) config.models = models;
  return config;
}

function managedBaseUrls(config: ProviderConfig): ReadonlySet<string> {
  const out = new Set<string>();
  if (config.baseUrl) out.add(config.baseUrl);
  for (const model of config.models ?? []) {
    if (model.baseUrl) out.add(model.baseUrl);
  }
  return out;
}

export function providerInfo(
  config: ProviderConfig,
  rewrite?: Omit<IntegrationProviderPayloadRewrite, "selectedModelID"> & { modelIds?: ReadonlySet<string> },
): GatewayProviderInfo {
  return {
    config,
    modelIds: rewrite?.modelIds,
    modelAliases: rewrite?.modelAliases,
    chatGPTModelIds: rewrite?.chatGPTModelIds,
    baseUrls: managedBaseUrls(config),
  };
}
